client: client.c utils.c common.h packet.h
	gcc -o client client.c utils.c

server: server.c utils.c common.h packet.h
	gcc -o server server.c utils.c

relay: relay.c utils.c common.h packet.h
	gcc -o relay relay.c utils.c
